### ISSUE TITLE
How to use it corretctly?

### ISSUE THREAD

**Issue by Bastiiiiii** [mdickinson/polyhedron#7] opened 2019-08-20 09:25 UTC
Sry, I do not get it.

Given a point p, how can I classify this point if it is "inside", "outside" or "boundary"?

I tried this (pcd=pointcloud, mesh_box = mesh from Open3D):
```
tetrahedron = Polyhedron(vertex_positions=np.asarray(mesh_box.vertices),triangles=np.asarray(mesh_box.triangles))

for i in range (int(len(np.asarray(pcd.points)))):
    p=np.asarray(pcd.points)[i]
    answer = tetrahedron.winding_number(p)
```
It always calculates a winding number equal to 0, which ist outside, but I am sure the points are inside (I made the box really big, that all points are inside).

Can you help me out?

Thank you!

**Comment by mdickinson** [comment] 2019-08-20 18:15
Can you tell me what `mesh_box.vertices`, `mesh_box.triangles` and `pcd.points` are? (I can't help without a way to reproduce.)

Note that the orientation of the triangles matters: a triangle `[0, 1, 2]` is not the same as the triangle `[0, 2, 1]`. That could be what's going wrong, but without seeing the data I can't really tell.

**Comment by Bastiiiiii** [comment] 2019-08-21 06:37
type(mesh_box.vertices)     <class 'open3d.open3d.utility.Vector3dVector'>
type(mesh_box.triangles)   <class 'open3d.open3d.utility.Vector3iVector'>
type(pcd.points)                 <class 'open3d.open3d.utility.Vector3dVector'>

Full Code:

```
from open3d import *
from fct_polyhedron import Polyhedron


mesh_box = create_mesh_box(width=1000, height=1000, depth=1000)
mesh_box.paint_uniform_color([0.9, 0.4, 0.1])

tetrahedron = Polyhedron(vertex_positions=np.asarray(mesh_box.vertices),triangles=np.asarray(mesh_box.triangles))

pcd = read_point_cloud("seg.ply")
# draw_geometries([pcd, mesh_box])

for i in range (int(len(np.asarray(pcd.points)))):
    p=np.asarray(pcd.points)[i]
    answer = tetrahedron.winding_number(p)
```
mesh_box is from Open3D: 
http://www.open3d.org/docs/release/python_api/open3d.geometry.create_mesh_box.html#open3d.geometry.create_mesh_box

**Comment by mdickinson** [comment] 2019-08-21 10:52
Thanks, but I really wanted to see the contents of the various arrays. Do you have a reproducible example that doesn't depend on any external libraries? It'll be a while before I have time to set up a test environment and install open3d in it - I can give you a much quicker answer if I don't have to do that.

**Comment by Bastiiiiii** [comment] 2019-08-21 11:13
**np.asarray(mesh_box.vertices)**
[[   0.    0.    0.]
 [1000.    0.    0.]
 [   0.    0. 1000.]
 [1000.    0. 1000.]
 [   0. 1000.    0.]
 [1000. 1000.    0.]
 [   0. 1000. 1000.]
 [1000. 1000. 1000.]]

**np.asarray(mesh_box.triangles)**
[[4 7 5]
 [4 6 7]
 [0 2 4]
 [2 6 4]
 [0 1 2]
 [1 3 2]
 [1 5 7]
 [1 7 3]
 [2 3 7]
 [2 7 6]
 [0 4 1]
 [1 4 5]]

**np.asarray(pcd.points)**
[[-7.5000000e-01  2.0625000e+00 -1.6000000e+01]
 [-6.8750000e-01  2.0625000e+00 -1.6000000e+01]
 [-6.2500000e-01  2.0625000e+00 -1.6000000e+01]
 [-5.6250000e-01  2.0625000e+00 -1.6000000e+01]
 [-7.5000000e-01  2.0000000e+00 -1.6000000e+01]
 [-6.8750000e-01  2.0000000e+00 -1.6000000e+01]
 [-6.2500000e-01  2.0000000e+00 -1.6000000e+01]
 [-5.6250000e-01  2.0000000e+00 -1.6000000e+01]
 [-5.0000000e-01  2.0000000e+00 -1.6000000e+01]
 [-1.9230800e-01  2.9807700e-01 -2.4615390e+00]
 [-1.8269200e-01  2.9807700e-01 -2.4615390e+00]
 [-1.0625000e+00  1.9375000e+00 -1.6000000e+01]
 [-1.0000000e+00  1.9375000e+00 -1.6000000e+01]
 [-8.7500000e-01  1.9375000e+00 -1.6000000e+01]
 [-8.1250000e-01  1.9375000e+00 -1.6000000e+01]
 [-7.5000000e-01  1.9375000e+00 -1.6000000e+01]
 [-6.8750000e-01  1.9375000e+00 -1.6000000e+01]
 [-6.2500000e-01  1.9375000e+00 -1.6000000e+01]
 [-5.6250000e-01  1.9375000e+00 -1.6000000e+01]
 [-5.0000000e-01  1.9375000e+00 -1.6000000e+01]
 [-4.3750000e-01  1.9375000e+00 -1.6000000e+01]
 [-1.9230800e-01  2.8846200e-01 -2.4615390e+00]
 [-1.8269200e-01  2.8846200e-01 -2.4615390e+00]
 [-1.1250000e+00  1.8750000e+00 -1.6000000e+01]
 [-1.0625000e+00  1.8750000e+00 -1.6000000e+01]
 [-1.0000000e+00  1.8750000e+00 -1.6000000e+01]
 [-9.3750000e-01  1.8750000e+00 -1.6000000e+01]
 [-8.7500000e-01  1.8750000e+00 -1.6000000e+01]
 [-8.1250000e-01  1.8750000e+00 -1.6000000e+01]
 [-7.5000000e-01  1.8750000e+00 -1.6000000e+01]
 [-6.8750000e-01  1.8750000e+00 -1.6000000e+01]
 [-6.2500000e-01  1.8750000e+00 -1.6000000e+01]
 [-5.6250000e-01  1.8750000e+00 -1.6000000e+01]
 [-5.0000000e-01  1.8750000e+00 -1.6000000e+01]
 [-4.3750000e-01  1.8750000e+00 -1.6000000e+01]
 [-1.8269200e-01  2.7884600e-01 -2.4615390e+00]
 [-1.1250000e+00  1.8125000e+00 -1.6000000e+01]
 [-2.2208800e-01  9.6560000e-03 -2.4719370e+00]
 [ 2.6250000e+00 -4.4375000e+00 -1.6000000e+01]
 [ 3.0000000e+00 -4.5625000e+00 -1.6000000e+01]
 [ 3.0625000e+00 -4.5625000e+00 -1.6000000e+01]
 [ 3.0625000e+00 -4.5625000e+00 -1.6000000e+01]
 [ 2.3529410e+00 -4.3529410e+00 -1.5058824e+01]
 [ 2.9375000e+00 -4.6250000e+00 -1.6000000e+01]
 [ 3.0000000e+00 -4.6250000e+00 -1.6000000e+01]
 [ 3.0000000e+00 -4.6250000e+00 -1.6000000e+01]
 [ 3.0000000e+00 -4.6250000e+00 -1.6000000e+01]
 [ 3.0625000e+00 -4.6250000e+00 -1.6000000e+01]
 [ 3.0625000e+00 -4.6250000e+00 -1.6000000e+01]
 [ 3.0625000e+00 -4.6250000e+00 -1.6000000e+01]
 [ 3.0625000e+00 -4.6250000e+00 -1.6000000e+01]
 [ 3.1250000e+00 -4.6250000e+00 -1.6000000e+01]
 [ 3.1875000e+00 -4.6250000e+00 -1.6000000e+01]
 [ 2.9473680e+00 -4.5112780e+00 -1.5398497e+01]
 [ 2.9473680e+00 -4.5112780e+00 -1.5398497e+01]
 [ 2.9473680e+00 -4.5112780e+00 -1.5398497e+01]
 [ 2.9473680e+00 -4.5112780e+00 -1.5398497e+01]
 [ 2.9962550e+00 -4.4943820e+00 -1.5340824e+01]
 [ 2.9962550e+00 -4.4943820e+00 -1.5340824e+01]
 [ 2.9962550e+00 -4.4943820e+00 -1.5340824e+01]
 [ 3.0561800e+00 -4.4943820e+00 -1.5340824e+01]
 [ 3.0561800e+00 -4.4943820e+00 -1.5340824e+01]
 [ 3.1161050e+00 -4.4943820e+00 -1.5340824e+01]
 [ 3.1161050e+00 -4.4943820e+00 -1.5340824e+01]
 [ 3.1760300e+00 -4.4943820e+00 -1.5340824e+01]
 [ 3.1760300e+00 -4.4943820e+00 -1.5340824e+01]
 [ 2.3682310e+00 -4.3898920e+00 -1.4787004e+01]
 [ 2.3682310e+00 -4.3898920e+00 -1.4787004e+01]
 [ 2.3682310e+00 -4.3898920e+00 -1.4787004e+01]
 [ 2.3682310e+00 -4.3898920e+00 -1.4787004e+01]
 [ 2.3682310e+00 -4.3898920e+00 -1.4787004e+01]
 [ 2.3682310e+00 -4.3898920e+00 -1.4787004e+01]
 [ 2.3682310e+00 -4.3898920e+00 -1.4787004e+01]
 [ 2.4347830e+00 -4.4057970e+00 -1.4840580e+01]
 [ 2.4347830e+00 -4.4057970e+00 -1.4840580e+01]
 [ 2.4347830e+00 -4.4057970e+00 -1.4840580e+01]
 [ 3.1176470e+00 -4.4705880e+00 -1.5058824e+01]
 [ 3.1764710e+00 -4.4705880e+00 -1.5058824e+01]
 [ 3.1764710e+00 -4.4705880e+00 -1.5058824e+01]
 [ 3.2352940e+00 -4.4705880e+00 -1.5058824e+01]
 [ 3.2352940e+00 -4.4705880e+00 -1.5058824e+01]
 [ 2.3345200e+00 -4.3843420e+00 -1.4576512e+01]
 [ 2.3345200e+00 -4.3843420e+00 -1.4576512e+01]
 [ 2.3345200e+00 -4.3843420e+00 -1.4576512e+01]
 [ 2.3345200e+00 -4.3843420e+00 -1.4576512e+01]
 [ 2.3345200e+00 -4.3843420e+00 -1.4576512e+01]
 [ 2.3345200e+00 -4.3843420e+00 -1.4576512e+01]
 [ 2.3345200e+00 -4.3843420e+00 -1.4576512e+01]
 [ 2.6086960e+00 -4.4637680e+00 -1.4840580e+01]
 [ 3.2000000e+00 -4.4800000e+00 -1.4894546e+01]
 [ 3.2000000e+00 -4.4800000e+00 -1.4894546e+01]
 [ 2.0069690e+00 -4.3484320e+00 -1.4271777e+01]
 [ 2.2937060e+00 -4.3636360e+00 -1.4321678e+01]
 [ 2.2937060e+00 -4.3636360e+00 -1.4321678e+01]
 [ 2.3496500e+00 -4.3636360e+00 -1.4321678e+01]
 [ 2.4788730e+00 -4.3943660e+00 -1.4422535e+01]
 [ 2.4788730e+00 -4.3943660e+00 -1.4422535e+01]
 [ 2.4788730e+00 -4.3943660e+00 -1.4422535e+01]
 [ 3.1654680e+00 -4.4892090e+00 -1.4733813e+01]
 [ 3.1654680e+00 -4.4892090e+00 -1.4733813e+01]
 [ 3.1654680e+00 -4.4892090e+00 -1.4733813e+01]
 [ 3.1654680e+00 -4.4892090e+00 -1.4733813e+01]
 [ 3.1654680e+00 -4.4892090e+00 -1.4733813e+01]
 [ 3.1654680e+00 -4.4892090e+00 -1.4733813e+01]
 [ 3.1654680e+00 -4.4892090e+00 -1.4733813e+01]
 [ 3.2924190e+00 -4.5054150e+00 -1.4787004e+01]
 [ 3.2924190e+00 -4.5054150e+00 -1.4787004e+01]
 [ 3.5362320e+00 -4.5217390e+00 -1.4840580e+01]
 [ 2.2777780e+00 -4.3888890e+00 -1.4222222e+01]
 [ 2.2777780e+00 -4.3888890e+00 -1.4222222e+01]
 [ 2.3333330e+00 -4.3888890e+00 -1.4222222e+01]
 [ 2.3333330e+00 -4.3888890e+00 -1.4222222e+01]
 [ 2.4444440e+00 -4.3888890e+00 -1.4222222e+01]
 [ 2.4444440e+00 -4.3888890e+00 -1.4222222e+01]
 [ 2.4444440e+00 -4.3888890e+00 -1.4222222e+01]
 [ 3.2340430e+00 -4.4822690e+00 -1.4524822e+01]
 [ 3.4857140e+00 -4.5142860e+00 -1.4628572e+01]
 [ 2.3172410e+00 -4.4137930e+00 -1.4124138e+01]
 [ 2.3172410e+00 -4.4137930e+00 -1.4124138e+01]
 [ 2.3172410e+00 -4.4137930e+00 -1.4124138e+01]
 [ 2.3172410e+00 -4.4137930e+00 -1.4124138e+01]
 [ 2.3172410e+00 -4.4137930e+00 -1.4124138e+01]
 [ 2.3172410e+00 -4.4137930e+00 -1.4124138e+01]
 [ 2.3172410e+00 -4.4137930e+00 -1.4124138e+01]
 [ 2.3724140e+00 -4.4137930e+00 -1.4124138e+01]
 [ 2.3724140e+00 -4.4137930e+00 -1.4124138e+01]
 [ 2.3724140e+00 -4.4137930e+00 -1.4124138e+01]
 [ 2.4275860e+00 -4.4137930e+00 -1.4124138e+01]
 [ 2.4275860e+00 -4.4137930e+00 -1.4124138e+01]
 [ 2.5467130e+00 -4.4290660e+00 -1.4173011e+01]
 [ 2.5467130e+00 -4.4290660e+00 -1.4173011e+01]
 [ 2.5467130e+00 -4.4290660e+00 -1.4173011e+01]
 [ 2.5467130e+00 -4.4290660e+00 -1.4173011e+01]
 [ 2.6020760e+00 -4.4290660e+00 -1.4173011e+01]
 [ 2.6020760e+00 -4.4290660e+00 -1.4173011e+01]
 [ 2.6020760e+00 -4.4290660e+00 -1.4173011e+01]
 [ 2.6020760e+00 -4.4290660e+00 -1.4173011e+01]
 [-2.6482760e+00 -4.4689660e+00 -1.4124138e+01]
 [ 2.3013700e+00 -4.4383560e+00 -1.4027397e+01]
 [ 2.3013700e+00 -4.4383560e+00 -1.4027397e+01]
 [ 2.3013700e+00 -4.4383560e+00 -1.4027397e+01]
 [ 2.3013700e+00 -4.4383560e+00 -1.4027397e+01]
 [ 2.3013700e+00 -4.4383560e+00 -1.4027397e+01]
 [ 2.3013700e+00 -4.4383560e+00 -1.4027397e+01]
 [ 2.3013700e+00 -4.4383560e+00 -1.4027397e+01]
 [ 2.3561640e+00 -4.4383560e+00 -1.4027397e+01]
 [ 2.4109590e+00 -4.4383560e+00 -1.4027397e+01]
 [ 2.4109590e+00 -4.4383560e+00 -1.4027397e+01]
 [ 2.4657530e+00 -4.4383560e+00 -1.4027397e+01]
 [ 2.4657530e+00 -4.4383560e+00 -1.4027397e+01]
 [ 2.5205480e+00 -4.4383560e+00 -1.4027397e+01]
 [ 2.5205480e+00 -4.4383560e+00 -1.4027397e+01]
 [ 2.5753420e+00 -4.4383560e+00 -1.4027397e+01]
 [ 2.6391750e+00 -4.4536080e+00 -1.4075602e+01]
 [ 2.6391750e+00 -4.4536080e+00 -1.4075602e+01]
 [ 2.6391750e+00 -4.4536080e+00 -1.4075602e+01]
 [ 2.6391750e+00 -4.4536080e+00 -1.4075602e+01]
 [ 2.6391750e+00 -4.4536080e+00 -1.4075602e+01]
 [ 2.6391750e+00 -4.4536080e+00 -1.4075602e+01]
 [ 2.6391750e+00 -4.4536080e+00 -1.4075602e+01]
 [-2.5931030e+00 -4.5241380e+00 -1.4124138e+01]
 [-2.5379310e+00 -4.5241380e+00 -1.4124138e+01]
 [-2.5379310e+00 -4.5241380e+00 -1.4124138e+01]
 [ 2.3401360e+00 -4.4625850e+00 -1.3931973e+01]
 [ 2.3401360e+00 -4.4625850e+00 -1.3931973e+01]
 [ 2.5578230e+00 -4.4625850e+00 -1.3931973e+01]
 [ 2.5578230e+00 -4.4625850e+00 -1.3931973e+01]
 [ 2.6211610e+00 -4.4778160e+00 -1.3979522e+01]
 [ 2.6211610e+00 -4.4778160e+00 -1.3979522e+01]
 [ 2.6211610e+00 -4.4778160e+00 -1.3979522e+01]
 [ 2.6211610e+00 -4.4778160e+00 -1.3979522e+01]
 [-2.5467130e+00 -4.5951560e+00 -1.4173011e+01]
 [-2.4827590e+00 -4.5793100e+00 -1.4124138e+01]
 [-2.4275860e+00 -4.5793100e+00 -1.4124138e+01]
 [ 2.5319860e+00 -4.4713800e+00 -1.3791245e+01]
 [ 2.5319860e+00 -4.4713800e+00 -1.3791245e+01]
 [ 2.5319860e+00 -4.4713800e+00 -1.3791245e+01]
 [ 2.5319860e+00 -4.4713800e+00 -1.3791245e+01]
 [ 2.5945940e+00 -4.4864860e+00 -1.3837838e+01]
 [ 2.5945940e+00 -4.4864860e+00 -1.3837838e+01]
 [ 2.6576270e+00 -4.5016950e+00 -1.3884746e+01]
 [ 2.6576270e+00 -4.5016950e+00 -1.3884746e+01]
 [ 2.7210880e+00 -4.5170070e+00 -1.3931973e+01]
 [ 2.7210880e+00 -4.5170070e+00 -1.3931973e+01]
 [ 2.7210880e+00 -4.5170070e+00 -1.3931973e+01]
 [ 2.7210880e+00 -4.5170070e+00 -1.3931973e+01]
 [ 2.8395910e+00 -4.5324230e+00 -1.3979522e+01]
 [ 2.8395910e+00 -4.5324230e+00 -1.3979522e+01]
 [ 2.8395910e+00 -4.5324230e+00 -1.3979522e+01]
 [ 2.8395910e+00 -4.5324230e+00 -1.3979522e+01]
 [ 2.8395910e+00 -4.5324230e+00 -1.3979522e+01]
 [ 2.8395910e+00 -4.5324230e+00 -1.3979522e+01]
 [ 2.8395910e+00 -4.5324230e+00 -1.3979522e+01]
 [ 2.8941980e+00 -4.5324230e+00 -1.3979522e+01]
 [ 2.8941980e+00 -4.5324230e+00 -1.3979522e+01]
 [-2.4275860e+00 -4.6344830e+00 -1.4124138e+01]
 [-2.3724140e+00 -4.6344830e+00 -1.4124138e+01]
 [ 2.6486490e+00 -4.5405410e+00 -1.3837838e+01]
 [ 2.6486490e+00 -4.5405410e+00 -1.3837838e+01]
 [ 2.6486490e+00 -4.5405410e+00 -1.3837838e+01]
 [ 2.6486490e+00 -4.5405410e+00 -1.3837838e+01]
 [ 2.9488060e+00 -4.5870310e+00 -1.3979522e+01]
 [ 3.0136990e+00 -4.6027400e+00 -1.4027397e+01]
 [ 3.0136990e+00 -4.6027400e+00 -1.4027397e+01]
 [ 3.0790380e+00 -4.6185560e+00 -1.4075602e+01]
 [ 3.1340210e+00 -4.6185560e+00 -1.4075602e+01]
 [-2.3172410e+00 -4.6896550e+00 -1.4124138e+01]
 [-2.2542960e+00 -4.6735400e+00 -1.4075602e+01]
 [ 2.9387760e+00 -4.6258500e+00 -1.3931973e+01]
 [ 2.9387760e+00 -4.6258500e+00 -1.3931973e+01]
 [ 3.0034130e+00 -4.6416380e+00 -1.3979522e+01]
 [ 3.0684930e+00 -4.6575340e+00 -1.4027397e+01]
 [ 3.0684930e+00 -4.6575340e+00 -1.4027397e+01]
 [ 3.1232880e+00 -4.6575340e+00 -1.4027397e+01]
 [-2.2620690e+00 -4.7448280e+00 -1.4124138e+01]
 [-2.1993130e+00 -4.7285220e+00 -1.4075602e+01]
 [-2.1369860e+00 -4.7123290e+00 -1.4027397e+01]
 [ 2.9288130e+00 -4.6644070e+00 -1.3884746e+01]
 [ 2.9288130e+00 -4.6644070e+00 -1.3884746e+01]
 [ 2.9931970e+00 -4.6802720e+00 -1.3931973e+01]
 [ 3.1126280e+00 -4.6962460e+00 -1.3979522e+01]
 [-2.1369860e+00 -4.7671230e+00 -1.4027397e+01]
 [-2.1369860e+00 -4.7671230e+00 -1.4027397e+01]
 [-2.0750850e+00 -4.7508530e+00 -1.3979522e+01]
 [-2.0067800e+00 -4.7186440e+00 -1.3884746e+01]
 [ 2.9830510e+00 -4.7186440e+00 -1.3884746e+01]
 [ 3.0372880e+00 -4.7186440e+00 -1.3884746e+01]
 [-2.0136050e+00 -4.7891150e+00 -1.3931973e+01]
 [-1.9459460e+00 -4.7567570e+00 -1.3837838e+01]
 [-1.8791950e+00 -4.7248320e+00 -1.3744967e+01]
 [-1.8791950e+00 -4.7785230e+00 -1.3744967e+01]
 [-1.8193980e+00 -4.7625420e+00 -1.3698997e+01]
 [-1.8193980e+00 -4.8160530e+00 -1.3698997e+01]
 [-1.7600000e+00 -4.8000000e+00 -1.3653334e+01]
 [-1.7066670e+00 -4.8000000e+00 -1.3653334e+01]
 [-1.7066670e+00 -4.8533330e+00 -1.3653334e+01]
 [-1.6533330e+00 -4.8533330e+00 -1.3653334e+01]
 [-1.6000000e+00 -4.8533330e+00 -1.3653334e+01]
 [-1.6000000e+00 -4.9066670e+00 -1.3653334e+01]
 [-2.3414600e-01 -9.2682900e-01 -2.4975610e+00]
 [-2.2208800e-01 -9.1732000e-01 -2.4719370e+00]
 [-2.2208800e-01 -9.2697600e-01 -2.4719370e+00]
 [-2.1153800e-01 -9.2307700e-01 -2.4615390e+00]
 [-2.0192300e-01 -9.2307700e-01 -2.4615390e+00]
 [-2.0192300e-01 -9.3269200e-01 -2.4615390e+00]
 [-1.9230800e-01 -9.3269200e-01 -2.4615390e+00]
 [-1.8269200e-01 -9.4230800e-01 -2.4615390e+00]
 [-9.2604500e-01 -5.0418000e+00 -1.3170418e+01]
 [-8.7459800e-01 -5.0932470e+00 -1.3170418e+01]
 [-7.6923100e-01 -5.1282050e+00 -1.3128205e+01]
 [-7.1565500e-01 -5.1629390e+00 -1.3086262e+01]
 [-6.6242000e-01 -5.1464970e+00 -1.3044586e+01]
 [-6.1146500e-01 -5.1974520e+00 -1.3044586e+01]
 [ 3.8323000e-02 -2.1077850e+00 -4.9053890e+00]
 [ 1.3837800e-01 -1.9545950e+00 -4.4281080e+00]
 [ 1.5335500e-01 -1.9254530e+00 -4.3620870e+00]
 [ 1.5335500e-01 -1.9424920e+00 -4.3620870e+00]
 [ 1.6877600e-01 -1.9240510e+00 -4.3206750e+00]
 [ 1.8565400e-01 -1.9240510e+00 -4.3206750e+00]
 [ 1.8565400e-01 -1.9409280e+00 -4.3206750e+00]
 [ 2.0062700e-01 -1.9226750e+00 -4.2800420e+00]
 [ 2.1010100e-01 -1.8585860e+00 -4.1373740e+00]
 [ 2.0062700e-01 -1.9393940e+00 -4.2800420e+00]
 [ 2.1010100e-01 -1.8747480e+00 -4.1373740e+00]
 [ 2.2626300e-01 -1.8747480e+00 -4.1373740e+00]
 [ 2.2626300e-01 -1.8909090e+00 -4.1373740e+00]
 [ 2.5396800e-01 -1.9809520e+00 -4.3343920e+00]
 [ 2.9090900e-01 -2.1272730e+00 -4.6545450e+00]
 [ 2.9090900e-01 -2.1454550e+00 -4.6545450e+00]
 [ 3.0909100e-01 -2.1454550e+00 -4.6545450e+00]
 [ 3.2690100e-01 -2.1430190e+00 -4.6492620e+00]
 [ 3.2690100e-01 -2.1611800e+00 -4.6492620e+00]
 [ 3.4428100e-01 -2.1562850e+00 -4.6387310e+00]
 [ 3.6158200e-01 -2.1514120e+00 -4.6282490e+00]]

**Comment by mdickinson** [comment] 2019-08-21 11:35
Thanks. It looks to me as though _all_ of your points have a negative coefficient in them somewhere (for example, the first point is `[-7.5000000e-01 2.0625000e+00 -1.6000000e+01]`, and the x and z coordinates are negative), so indeed they're all outside the cube, and I'd expect to get a winding number of 0 in each case.

What happens if you test with a point *inside* the cube?

**Comment by mdickinson** [comment] 2019-09-11 17:47
@Bastiiiiii Did my answer resolve your question? I'm going to close this issue, because I don't see any evidence of a problem with the library code here: all the points you show *are* outside the cube you're testing against, so `0` is the correct answer in each case.

**Closed as completed by mdickinson** 2019-09-11 17:47 UTC

**Comment by Bastiiiiii** [comment] 2019-09-11 17:54
@mdickinson Thank you very much! Now it works.
 The code above were only a example and I made a different mistake in the original code. But I found it.
